"""Plotly map figure construction for the dashboard."""

from __future__ import annotations

import pandas as pd
import plotly.express as px

from features.config import (
    CLASS_COLORS,
    CLASS_ORDER,
    MAP_DEFAULT_HEIGHT,
    MAP_DEFAULT_MARKER_SIZE,
    WI_CENTER,
)


def build_map(
    map_df: pd.DataFrame,
    disease_label: str,
    color_overrides: dict[str, str] | None = None,
    icon: str = "📡",
    marker_size: int = MAP_DEFAULT_MARKER_SIZE,
    height: int = MAP_DEFAULT_HEIGHT,
):
    """Build the interactive station map for one selected disease.

    Renders a ``scatter_mapbox`` with one marker per station, colored
    by ``risk_class``. An emoji icon is overlaid on each marker so
    points read as weather stations rather than generic dots. The
    legend shows only classes actually present in the data, in
    risk-priority order, and hover tooltips surface station metadata
    plus the formatted risk value.

    Args:
        map_df: DataFrame from :func:`features.data.prepare_disease_df`.
            Must include ``latitude``, ``longitude``, ``risk_class``,
            ``risk_display``, and the station metadata columns.
        disease_label: Human-readable disease name, used in the legend title.
        color_overrides: Optional ``{risk_class: hex}`` map merged on top
            of :data:`CLASS_COLORS`. Lets the sidebar UI retheme the
            map without editing config.
        icon: Emoji rendered on each marker (see ``ICON_CHOICES``).
        marker_size: Marker radius in pixels.
        height: Figure height in pixels — bump up for a more horizontal layout.

    Returns:
        A configured ``plotly.graph_objects.Figure`` ready for
        ``st.plotly_chart``.
    """
    colors = {**CLASS_COLORS, **(color_overrides or {})}
    present_classes = [c for c in CLASS_ORDER if c in map_df["risk_class"].unique()]

    # Carrying the icon as a column lets plotly broadcast it correctly
    # across the per-class traces generated by ``color=``.
    plot_df = map_df.copy()
    plot_df["__icon"] = icon

    fig = px.scatter_mapbox(
        plot_df,
        lat="latitude",
        lon="longitude",
        color="risk_class",
        color_discrete_map=colors,
        category_orders={"risk_class": present_classes},
        hover_name="station_name",
        hover_data={
            "station_id": True,
            "city": True,
            "county": True,
            "region": True,
            "risk_class": True,
            "risk_display": True,
            "latitude": False,
            "longitude": False,
            "__icon": False,
        },
        text="__icon",
        zoom=6.0,
        height=height,
    )
    fig.update_traces(
        mode="markers+text",
        textposition="middle center",
        marker=dict(size=marker_size, opacity=0.9),
        textfont=dict(size=int(marker_size * 0.55)),
    )
    fig.update_layout(
        mapbox_style="open-street-map",
        mapbox_center=WI_CENTER,
        margin={"r": 0, "t": 0, "l": 0, "b": 0},
        legend=dict(
            title_text=f"{disease_label} risk",
            orientation="v",
            yanchor="top",
            y=0.99,
            xanchor="left",
            x=0.01,
            bgcolor="rgba(255,255,255,0.85)",
        ),
    )
    return fig
